---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: install filebeat deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: sudo metricbeat modules enable docker

  - name: setup filebeat
    command: sudo metricbeat setup

  - name: start filebeat service
    command: sudo service metricbeat start

  - name: enable service filebeat on boot
    systemd:
      name: metricbeat
      enabled: yes
